#Python Image
FROM python:3.11-slim

#Set Dir
WORKDIR /App

#Copy
COPY .  .

#Dependency install
RUN pip install --no-cache-dir -r requirements.txt

#Streamlit port
EXPOSE 8501

#Run App

CMD ["streamlit", "run", "CryptoDashboard/App/Dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]